# Generated by Django 5.0.6 on 2026-07-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_mac', models.CharField(blank=True, max_length=30, null=True)),
                ('destination_mac', models.CharField(blank=True, max_length=30, null=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ARP', 'ARP'), ('DNS', 'DNS'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_flags', models.CharField(blank=True, max_length=50, null=True)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('packet_length', models.PositiveIntegerField()),
                ('interface', models.CharField(default='Unknown', max_length=100)),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_capture', models.BooleanField(default=False)),
                ('threat_detection', models.BooleanField(default=False)),
                ('alert_engine', models.BooleanField(default=False)),
                ('machine_learning', models.BooleanField(default=False)),
                ('packets_today', models.PositiveIntegerField(default=0)),
                ('threats_today', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_name', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='monitoring.packetlog')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Dashboard', 'Dashboard'), ('Email', 'Email'), ('SMS', 'SMS')], default='Dashboard', max_length=20)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.threat')),
            ],
        ),
    ]
